services:
  app:
    build:
      context: .
      args:
        - OCEAN_API_URL=${OCEAN_API_URL}
        - ANONYM_TOKEN=${ANONYM_TOKEN}
        - ANONYM_ALLOWED=${ANONYM_ALLOWED}
        - GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID}
    image: krre/ocean-web:1.0
