services:
  app:
    build:
      context: .
      args:
        - PUBLIC_OCEAN_API_URL=${PUBLIC_OCEAN_API_URL}
        - PUBLIC_ANONYM_TOKEN=${PUBLIC_ANONYM_TOKEN}
        - PUBLIC_ANONYM_ALLOWED=${PUBLIC_ANONYM_ALLOWED}
    image: krre/ocean-web:1.0
